On demand maps
cmu-sei/Player.Api pull request #21
Opened 2021-05-04 16:06 UTC by sei-byoung

Implement the ability to subscribe to events in Player. Apps can supply the URL to a callback, which will be called when the relevant event occurs.

2021-05-04 18:08 UTC, sei-ebram approved these changes

2021-05-06 14:32 UTC, sei-tspencer approved these changes

2021-05-06 14:40 UTC, sei-aschlackman requested changes

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api.Data/Data/Models/View.cs
> +            entity.Id = Guid.NewGuid();
Does it work without this after the transaction interceptor change?

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Controllers/WebhookController.cs
> +}
Is there no way to update an existing subscription? For example, to add or remove subscribed event types?

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/BackgroundServices/BackgroundWebhookService.cs
> +            var success = _eventQueue.Post(t);
I think this should use SendAsync, to answer the comment.

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/BackgroundServices/BackgroundWebhookService.cs
> +            _eventQueue = new ActionBlock<Task>(t => t.Start());
I think it makes more sense for this to accept an event object or id and have the ActionBlock call ProcessEvent. Passing in an arbitrary Task is a little too generic and puts a lot on the caller of the method.

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/BackgroundServices/BackgroundWebhookService.cs
> +                            webhookEvent.Timestamp = DateTime.Now;
This should be DateTime.UtcNow

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/BackgroundServices/BackgroundWebhookService.cs
> +                            var webhookEvent = new ViewModels.Webhooks.WebhookEvent();
Would it be possible for the WebhookEvent to be created by the event handler and added as a serialized object to the PendingEvent in the database, so the background worker can just pull it out and send it and not have to be updated for every new event type?

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/BackgroundServices/BackgroundWebhookService.cs
> +        private async Task<string> getAuthToken(string clientId, string clientSecret, string tokenUrl)
This method could maybe be simplified a bit by using the [IdentityModel](https://www.nuget.org/packages/IdentityModel/) package similar to [in Caster here](https://github.com/cmu-sei/Caster.Api/blob/development/src/Caster.Api/Domain/Services/AuthenticationService.cs#L79)

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/BackgroundServices/BackgroundWebhookService.cs
> +        {
We should also consider caching the token per client, but that can be a separate PR

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/DbInterceptors/ViewHandler.cs
> +            eventEntity.Timestamp = DateTime.Now;
This should be DateTime.UtcNow

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/DbInterceptors/ViewHandler.cs
> +            Task t = new Task(async eventId => await _backgroundService.ProcessEvent((Guid) eventId), eventEntity.Id, new CancellationToken());
Like I said above, this is kind of clunky. Would be nice to just do something like _backgroundService.AddEvent(event) or AddEvent(eventId).

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/Extensions/DatabaseExtensions.cs
> +                    var backgroundService = services.GetService<IBackgroundWebhookService>();
Why is this here?

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Infrastructure/Mappings/ViewProfile.cs
> +                .ForMember(dest => dest.ParentViewId, opt => opt.MapFrom(src => src.ViewId));
Why not have these names match? ParentViewId on the entity as well probably makes sense?

2021-05-06 14:40 UTC, sei-aschlackman commented on Player.Api/Services/WebhookService.cs
> +    public class WebhookService : IWebhookService
Need to add auth checks for these methods?

2022-09-22 14:32 UTC, sei-aschlackman commented
Superseeded by https://github.com/cmu-sei/Player.Api/pull/32

2022-09-22 14:32 UTC, closed without merging