Migrate to dotnet 3.1
cmu-sei/Player.Api pull request #7
Opened 2020-10-23 16:23 UTC by sei-ebram

2020-10-29 14:25 UTC, sei-chershberger approved these changes

2020-11-02 16:13 UTC, sei-aschlackman requested changes

2020-11-02 16:13 UTC, sei-aschlackman commented on Player.Api/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> -                c.OperationFilter<DefaultResponseOperationFilter>();
I think this still needs to be here, or the default error response doesn't show up in the swagger docs.

2020-11-02 16:13 UTC, sei-aschlackman commented on Player.Api/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> -                c.OperationFilter<DefaultResponseOperationFilter>();
Also need a c.EnableAnnotations() or the OperationIds don't get used.

2020-11-02 16:23 UTC, sei-aschlackman commented
Probably also would be a good time to change ApiError to ProblemDetails in JsonExceptionFilter.cs and get rid of the redundant ApiError now. I don't think it should break anything since they are basically the same thing.

2020-11-04 14:51 UTC, sei-noconnor approved these changes

2020-11-04 15:10 UTC, sei-aschlackman approved these changes

2020-11-04 17:46 UTC, merged