File upload
cmu-sei/Player.Api pull request #9
Opened 2021-01-12 15:05 UTC by sei-byoung

Implement endpoints necessary for file upload functionality

2021-01-12 15:34 UTC, sei-tspencer approved these changes

2021-01-12 15:34 UTC, sei-tspencer commented on Player.Api/Services/FileService.cs
> +                // ID is set here so we can return a list of the uploaded files without calling save changes more than once
Nice technique!

2021-01-12 15:34 UTC, sei-tspencer commented on Player.Api/Services/FileService.cs
> +            foreach (var team in teams)
perhaps call GetByTeamAsync instead of duplicating its code here?

2021-01-12 15:34 UTC, sei-tspencer commented on Player.Api/player/views/453d394e-bf18-499b-9786-149b0f8d69ec/file
> +Add files upload step to edit view screen
was this file intended to be included?  update .gitignore?

2021-01-14 16:19 UTC, sei-ebram reviewed
lots of new files without header.  also make sure it's all the new header:
  
// Copyright 2021 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.

2021-01-14 16:19 UTC, sei-ebram commented on Player.Api.Data/Data/Models/File.cs
> +/*
new header is:

  
// Copyright 2021 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.

2021-01-14 16:19 UTC, sei-ebram commented on Player.Api.Migrations.PostgreSQL/Migrations/20201229140841_CloneField.cs
> +﻿using System;
new header is:

  
// Copyright 2021 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.

2021-01-14 16:43 UTC, sei-ebram commented on Player.Api/appsettings.json
> +    "basePath": "C:\\SEI\\Tools\\Code\\FileUploads",
we'll want to change this path.  @sei-aschlackman suggestions?

2021-01-14 17:28 UTC, sei-aschlackman requested changes

2021-01-14 17:28 UTC, sei-aschlackman commented on Player.Api/Services/ViewService.cs
> +            // Need a second SaveChanges bc we don't know new id until saved
I think if you reference the virtual Team or View property instead of the id directly, EF will fill in the id after a single SaveChanges.

2021-01-14 17:30 UTC, sei-aschlackman commented on Player.Api/appsettings.json
> +    "basePath": "C:\\SEI\\Tools\\Code\\FileUploads",
something like player/files like how we use player/isos in [Vm.Api](https://github.com/cmu-sei/Vm.Api/blob/development/src/Player.Vm.Api/appsettings.json#L51)?

2021-01-14 17:38 UTC, sei-aschlackman commented on Player.Api/Services/FileService.cs
> +            // This authorization check assumes all teams for the file are in the same view
We should probably enforce this check, otherwise someone could add a file to a view they don't have access to using the api by including some teams in a different view

2021-01-14 17:40 UTC, sei-aschlackman commented on Player.Api/Services/FileService.cs
> +        public async Task<IEnumerable<FileModel>> UploadAsync(FileForm form, CancellationToken ct)
I think we need to check that the user is allowed to upload to the teams in the form here? Or verify that the teams are all in the same view and the user has access to upload to that view.

2021-01-19 15:04 UTC, sei-noconnor approved these changes

2021-01-20 15:22 UTC, merged